"""add fcm_token to residents and admins

Revision ID: 4f2a38d2c27f
Revises: 98d99a5e09a6
Create Date: 2026-07-31 10:22:09.667993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2a38d2c27f'
down_revision: Union[str, Sequence[str], None] = '98d99a5e09a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: removed an autogenerated `alter_column('admins', 'role', ...)`
    # here — same recurring SQLite-only autogenerate false positive.
    op.add_column('admins', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    op.add_column('residents', sa.Column('fcm_token', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('residents', 'fcm_token')
    op.drop_column('admins', 'fcm_token')
