"""add complaint enhancement fields, internal notes, audit log

Revision ID: 82cdc490b76b
Revises: b59d6b73c399
Create Date: 2026-07-25 10:01:20.102333

NOTE: this migration was hand-corrected after reviewing the autogenerated
version, for two reasons:

1. Autogenerate wanted to `ALTER COLUMN admins.role TYPE <new enum>` —
   risky on Postgres, since changing a column to a differently-shaped
   native ENUM type is not a simple operation and risks failure or data
   loss. Adding new values to an EXISTING Postgres enum type only needs
   `ALTER TYPE ... ADD VALUE`, which is safe and additive. This migration
   uses that instead, guarded to only run on Postgres (SQLite has no
   native enum type, so no action is needed there at all).
2. Autogenerate's new `complaints.priority` and
   `complaints.closed_by_resident_early` columns were NOT NULL with no
   default — this would fail against any existing rows in the real
   Supabase database. Both now have explicit `server_default` values.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '82cdc490b76b'
down_revision: Union[str, Sequence[str], None] = 'b59d6b73c399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('actor_admin_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=80), nullable=False),
        sa.Column('entity_type', sa.String(length=50), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_admin_id'), 'audit_logs', ['actor_admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)

    op.create_table('complaint_internal_notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('complaint_id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('note', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
        sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_internal_notes_complaint_id'), 'complaint_internal_notes', ['complaint_id'], unique=False)

    # Additive-only enum extension on Postgres; no-op on SQLite (no native enum type there).
    # Labels are UPPERCASE (matching the Python enum MEMBER NAMES, e.g. 'MAINTENANCE_ADMIN')
    # because that's what SQLAlchemy actually uses for native Postgres enum types by
    # default — confirmed directly against this project's existing deployed enums
    # (ComplaintStatus's real labels are 'PENDING', 'ACCEPTED', etc., not lowercase)
    # before writing this, not assumed.
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE adminrole ADD VALUE IF NOT EXISTS 'MAINTENANCE_ADMIN'")
        op.execute("ALTER TYPE adminrole ADD VALUE IF NOT EXISTS 'SUPPORT_STAFF'")

    # `op.add_column` does NOT auto-create a new Postgres enum TYPE the way
    # `op.create_table` does — it has to be created explicitly first, or
    # Postgres errors with "type does not exist". This is the actual fix
    # for that error (caught from a real run against the live database).
    complaint_priority_enum = postgresql.ENUM('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='complaintpriority')
    if bind.dialect.name == "postgresql":
        complaint_priority_enum.create(bind, checkfirst=True)

    # server_default ensures this succeeds against existing rows in production.
    op.add_column('complaints', sa.Column(
        'priority', complaint_priority_enum,
        nullable=False, server_default='NORMAL',
    ))
    op.add_column('complaints', sa.Column('assigned_admin_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column(
        'closed_by_resident_early', sa.Boolean(), nullable=False, server_default=sa.false(),
    ))
    op.add_column('complaints', sa.Column('early_close_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_complaints_assigned_admin_id'), 'complaints', ['assigned_admin_id'], unique=False)
    op.create_index(op.f('ix_complaints_priority'), 'complaints', ['priority'], unique=False)

    # batch_alter_table so this works on SQLite too (which has no native
    # ALTER TABLE ADD CONSTRAINT support and requires Alembic's batch/
    # copy-and-recreate strategy) as well as Postgres (batch mode simply
    # falls through to a normal ALTER TABLE there).
    with op.batch_alter_table('complaints') as batch_op:
        batch_op.create_foreign_key('fk_complaints_assigned_admin_id_admins', 'admins', ['assigned_admin_id'], ['id'])


def downgrade() -> None:
    bind = op.get_bind()
    with op.batch_alter_table('complaints') as batch_op:
        batch_op.drop_constraint('fk_complaints_assigned_admin_id_admins', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_priority'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_admin_id'), table_name='complaints')
    op.drop_column('complaints', 'early_close_reason')
    op.drop_column('complaints', 'closed_by_resident_early')
    op.drop_column('complaints', 'assigned_admin_id')
    op.drop_column('complaints', 'priority')
    if bind.dialect.name == "postgresql":
        postgresql.ENUM(name='complaintpriority').drop(bind, checkfirst=True)
    # Note: Postgres doesn't support removing enum values, so the added
    # 'maintenance_admin'/'support_staff' labels on adminrole intentionally
    # stay even on downgrade — this is standard practice for Postgres enums.
    op.drop_index(op.f('ix_complaint_internal_notes_complaint_id'), table_name='complaint_internal_notes')
    op.drop_table('complaint_internal_notes')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
