"""add push_token to residents and admins

Revision ID: 98d99a5e09a6
Revises: c9f11f4c3b0e
Create Date: 2026-07-26 11:21:48.644307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d99a5e09a6'
down_revision: Union[str, Sequence[str], None] = 'c9f11f4c3b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: removed an autogenerated `alter_column('admins', 'role', ...)`
    # here — same SQLite-only false positive documented in earlier
    # migrations (c9f11f4c3b0e), not a real schema difference.
    op.add_column('admins', sa.Column('push_token', sa.String(length=255), nullable=True))
    op.add_column('residents', sa.Column('push_token', sa.String(length=255), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('residents', 'push_token')
    op.drop_column('admins', 'push_token')
