"""add society_info and prayer_timings tables

Revision ID: b59d6b73c399
Revises: 8c790bdaf448
Create Date: 2026-07-25 06:22:32.623644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59d6b73c399'
down_revision: Union[str, Sequence[str], None] = '8c790bdaf448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prayer_timings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mosque_name', sa.Enum('BILAL_MOSQUE', 'MARKAZI_JAMIA_MOSQUE', name='mosquename'), nullable=False),
    sa.Column('fajr', sa.String(length=20), nullable=False),
    sa.Column('zuhr', sa.String(length=20), nullable=False),
    sa.Column('asr', sa.String(length=20), nullable=False),
    sa.Column('maghrib', sa.String(length=20), nullable=False),
    sa.Column('isha', sa.String(length=20), nullable=False),
    sa.Column('jummah', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_admin_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mosque_name')
    )
    op.create_table('society_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_text', sa.Text(), nullable=False),
    sa.Column('secretary_name', sa.Text(), nullable=True),
    sa.Column('secretary_designation', sa.Text(), nullable=True),
    sa.Column('deputy_chairman_name', sa.Text(), nullable=True),
    sa.Column('deputy_chairman_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('society_info')
    op.drop_table('prayer_timings')
    # ### end Alembic commands ###
