"""replace AWC employee fields with cnic on residents

Revision ID: b7d3f21ac845
Revises: a1c4e7f92b03
Create Date: 2026-08-05 09:30:00.000000

Hand-written rather than autogenerated, following this project's convention
(SQLite autogenerate has produced spurious diffs here before, e.g. the
phantom `admins.role` change).

Adds `residents.cnic` and drops `residents.is_employee` /
`residents.employee_number`.

`cnic` is nullable because residents who registered before this field
existed have no value for it. The registration API requires it for all new
registrations, so only pre-existing rows can be NULL.

NOTE: dropping the two employee columns discards that data permanently.
That is intended — employee status did not feed into the complaint flow and
is no longer collected. The downgrade recreates the columns but cannot
recover their previous contents.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d3f21ac845'
down_revision: Union[str, Sequence[str], None] = 'a1c4e7f92b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('residents', sa.Column('cnic', sa.String(length=13), nullable=True))
    op.create_index(op.f('ix_residents_cnic'), 'residents', ['cnic'], unique=False)

    op.drop_column('residents', 'employee_number')
    op.drop_column('residents', 'is_employee')


def downgrade() -> None:
    # Recreates the columns so the schema matches again, but the original
    # values are gone — they were dropped, not archived.
    op.add_column(
        'residents',
        sa.Column('is_employee', sa.Boolean(), nullable=True, server_default=sa.false()),
    )
    op.add_column('residents', sa.Column('employee_number', sa.String(length=50), nullable=True))

    op.drop_index(op.f('ix_residents_cnic'), table_name='residents')
    op.drop_column('residents', 'cnic')
