"""add chairman fields and secretary message to society_info

Revision ID: c9f11f4c3b0e
Revises: 82cdc490b76b
Create Date: 2026-07-25 11:21:51.638182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f11f4c3b0e'
down_revision: Union[str, Sequence[str], None] = '82cdc490b76b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE: removed an autogenerated `alter_column('admins', 'role', ...)`
    # here — it's a false positive from SQLite's autogenerate comparison
    # (SQLite has no real enum type, so it always looks "different" from
    # the Python model); the actual admin role addition was already
    # correctly applied via raw ALTER TYPE in migration 82cdc490b76b.
    op.add_column('society_info', sa.Column('chairman_name', sa.Text(), nullable=True))
    op.add_column('society_info', sa.Column('chairman_message', sa.Text(), nullable=True))
    op.add_column('society_info', sa.Column('secretary_message', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('society_info', 'secretary_message')
    op.drop_column('society_info', 'chairman_message')
    op.drop_column('society_info', 'chairman_name')
